language: php

services:
  - mysql

before_script:
  - echo "[mysql]\nhost = localhost\nuser = root\npassword = \n" > amisstestrc

php:
  - "nightly"
  - "hhvm"
  - 5.6
  - 5.5
  - 5.4

branches:
  only:
    - master
    - develop

script: php test/run.php --with-mysql --exclude-group=faulty,faulty-sqlite,faulty-mysql

